bt_block_card.settings:
  type: config_object
  label: 'Bootstrap Toolbox Block to Card Settings'
  mapping:
    theme_as_card:
      type: boolean
      label: 'Theme as a card'
      default_value: false
    card_classes:
      type: boolean
      label: 'Card classes'
      default_value: false
    header_classes:
      type: boolean
      label: 'Header classes'
      default_value: false
    body_classes:
      type: boolean
      label: 'Body classes'
      default_value: false


